export const servicesData =  {
    categories: ['All', 'Appetizer', 'Pizza', 'Dessert'],
    services: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'Sauna', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 2, image: '/assets/img/Services/pizza-1.jpg', title: 'Cheese', category: 'Pizza', description: 'A description of our service...', cost: '$18' },
        { id: 3, image: '/assets/img/Services/pizza-2.jpg', title: 'Pepperoni', category: 'Pizza', description: 'A description of our service...', cost: '$20' },
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Swedish Massage', category: 'Massage', description: 'A description of our service...', cost: 8000 },
        { id: 5, image: '/assets/img/Services/pizza-3.jpg', title: 'Sausage', category: 'Pizza', description: 'A description of our service...', cost: '$20' },
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Facial ', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 7, image: '/assets/img/Services/pizza-4.jpg', title: 'Combo', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'Candlelight Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 9, image: '/assets/img/Services/pizza-5.jpg', title: 'Veggie', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: 'Pedicure', category: 'Ammenities', description: 'A description of our service...', cost: 4000 },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Girls Day', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 12, image: '/assets/img/Services/pizza-6.jpg', title: 'Margherita', category: 'Pizza', description: 'A description of our service...', cost: '$18' },
        { id: 13, image: '/assets/img/Services/pizza-7.jpg', title: 'Hawaiian', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 14, image: '/assets/img/Services/pizza-8.jpg', title: 'Meat Lovers', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Full Body Scrub', category: 'Ammenities', description: 'A description of our service...', cost: 9000 },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Deep tissue', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 17, image: '/assets/img/Services/service-17.jpg', title: 'Hot Stone Massage', category: 'Massage', description: 'A description of our service...', cost: 9000 },
        { id: 18, image: '/assets/img/Services/pizza-9.jpg', title: 'Pesto', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 19, image: '/assets/img/Services/pizza-10.jpg', title: 'White', category: 'Pizza', description: 'A description of our service...', cost: '$23' },
        { id: 20, image: '/assets/img/Services/service-20.jpg', title: 'Reflexology', category: 'Ammenities', description: 'A description of our service...', cost: 2000 },
    ],
}