export const servicesData =  {
    categories: ['All', 'Appetizer', 'Pizza', 'Dessert'],
    services: [
        { id: 1, image: '/assets/img/Services/service-1.jpg', title: 'House Salad', category: 'Appetizer', description: 'house made salad with spinach, romaine, avocado, red onion, tomato & italian dressing', cost: '$6' },
        { id: 2, image: '/assets/img/Services/pizza-1.jpg', title: 'Cheese', category: 'Pizza', description: 'tomato sauce, mozzarella & basil', cost: '$18' },
        { id: 3, image: '/assets/img/Services/pizza-2.jpg', title: 'Pepperoni', category: 'Pizza', description: 'tomato sauce, mozzarella & pepperoni', cost: '$20' },
        { id: 4, image: '/assets/img/Services/service-4.jpg', title: 'Tiramisu', category: 'Dessert', description: 'house mad tiramisu slice', cost: '$8' },
        { id: 5, image: '/assets/img/Services/pizza-3.jpg', title: 'Sausage', category: 'Pizza', description: 'tomato sauce, mozzarella, house made sausage', cost: '$20' },
        { id: 6, image: '/assets/img/Services/service-6.jpg', title: 'Caesar Salad', category: 'Appetizer', description: 'romaine lettuce with croutons & house made caesar dressing', cost: '$6' },
        { id: 7, image: '/assets/img/Services/pizza-4.jpg', title: 'Combo', category: 'Pizza', description: 'tomato sauce, mozzarella, pepperoni, sausage, olive, red onion, red pepper, & basil', cost: '$23' },
        { id: 8, image: '/assets/img/Services/service-8.jpg', title: 'Red Velvet Cake', category: 'Dessert', description: '1 slice hosue made red velvet cake with cream cheese frosting', cost: '$8' },
        { id: 9, image: '/assets/img/Services/pizza-5.jpg', title: 'Veggie', category: 'Pizza', description: 'tomato sauce, mozzarella, green pepper, red pepper, olive, onion & basil', cost: '$23' },
        { id: 10, image: '/assets/img/Services/service-10.jpg', title: '6pc Wings', category: 'Appetizer', description: '6 bone-in wings in our house made buffalo sauce', cost: '$10' },
        { id: 11, image: '/assets/img/Services/service-11.jpg', title: 'Breadsticks', category: 'Appetizer', description: '6 garlic breadsticks', cost: '$6' },
        { id: 12, image: '/assets/img/Services/pizza-6.jpg', title: 'Margherita', category: 'Pizza', description: 'tomato sauce, fresh slices of mozzarella & basil', cost: '$18' },
        { id: 13, image: '/assets/img/Services/pizza-7.jpg', title: 'Hawaiian', category: 'Pizza', description: 'tomato sauce, mozzarella, ham, pineapple, & basil', cost: '$23' },
        { id: 14, image: '/assets/img/Services/pizza-8.jpg', title: 'Meat Lovers', category: 'Pizza', description: 'tomato sauce, mozzarella, house made sausage, pepperoni & ham', cost: '$23' },
        { id: 15, image: '/assets/img/Services/service-15.jpg', title: 'Mozzarella Sticks', category: 'Appetizer', description: '6 mozzarella sticks with house made marinara sauce', cost: '$6' },
        { id: 16, image: '/assets/img/Services/service-16.jpg', title: 'Strawberry Panna Cotta', category: 'Dessert', description: 'home made panna cotta', cost: '$6' },
        { id: 17, image: '/assets/img/Services/service-17.jpg', title: 'Cannoli', category: 'Dessert', description: 'house made chocolate cannoli', cost: '$6' },
        { id: 18, image: '/assets/img/Services/pizza-9.jpg', title: 'Pesto', category: 'Pizza', description: 'pesto sauce, tomato, spinach, red onion, mozzarella & basil', cost: '$23' },
        { id: 19, image: '/assets/img/Services/pizza-10.jpg', title: 'White', category: 'Pizza', description: 'fontina, mozzarella, ricotta, parmesan & parsley', cost: '$23' },
        { id: 20, image: '/assets/img/Services/service-20.jpg', title: 'French Fries', category: 'Appetizer', description: 'crispy french fries with garlic & parsley', cost: '$6' },
    ],
}